<?php
// lock:0
// inc:6-----------------------------
// row_count:5-----------------------------
// --- start headers ---
// table:content
// columns:1:id:int:0|2:name:string:1|3:content:string:0
// ---
// ---
// --- end headers ---
// row:1`1`|2`header intro`|3`<h1>razorCMS V3</h1><p>File Based Content Management System (FBCMS)</p>`
// row:1`2`|2`Main content - In the beginning`|3`<h3><i class="fa fa-leaf"></i> In The Beginning...</h3><p>razorCMS began as a databaseless flat file content management system, forked from a project called uCMS. It's structure allowed you to have just the amount of functionality you needed in a flat file CMS solution, adding extensions (blade packs) for further functionality, whilst allowing setup on simple servers with no database.</p><p>Starting with a core system install, razorCMS gave you base functionality required to run a website, add the extra functionality as you needed it via the blade pack management system. Everything from WYSIWYG editors to SEF URL was added as extra functionality.</p>`
// row:1`3`|2`Main content - the future`|3`<h3><i class="fa fa-rocket"></i> Looking Forward...</h3><p>Since its conception, technology has changed dramatically, with more and more functionality being handled via JavaScript. In addition to this, a more modular object based approached can be used to make things more extendible, allowing for integration with other technologies like mobile applications.</p><p>With all this in mind, razorCMS V3 was born, utilising technologies like angularJS, PHP and RESTfull approaches to dealing with data management. Yes we are still a file based CMS, but we are no longer flat file, adapting a new method for file based DB storage.</p>`
// row:1`4`|2`Main content - various stuff`|3`<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>This is a paragraph with a <a href="http://v3.razorcms.co.uk">link to razorcms V3</a> this paragraph has lots of text <i>some is italic</i>, some is underlined and <b>some is bold</b> in it to show how a paragraph looks when adding text to the system. This paragraph has lots of text in it to show how a paragraph looks when adding text to the system. This paragraph has lots of text in it to show how a paragraph looks when adding text to the system.</p><p></p><ol><li>This is an item</li><li>Another</li><li>And another</li></ol><div><ul><li>Bullet point</li><li>Another</li><li>And another</li></ul><div></div></div><p></p><table class="table table-bordered table-striped table-condensed" width="100%"><thead><tr><th width="50%">Header</th><th width="50%">Header</th></tr></thead><tbody><tr><td width="50%" class="even">Content</td><td width="50%" class="even">Content</td></tr><tr><td width="50%" class="odd">Content</td><td width="50%" class="odd">Content</td></tr><tr><td width="50%" class="even">Content</td><td width="50%" class="even">Content</td></tr><tr><td width="50%" class="odd">Content</td><td width="50%" class="odd">Content</td></tr><tr><td width="50%" class="even">Content</td><td width="50%" class="even">Content</td></tr></tbody></table>`
// row:1`5`|null|3`<div class="well"><p>This is some text to go in here and I have put it in a well</p></div>`